language: node_js
node_js:
  - "6"
  - "5"
  - "node" # latest stable

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - psql -c 'create database db_test;' -U postgres
  - "export NODE_ENV=ci-travis"
  - npm run db:migrate
  - npm run db:seed
  - npm run build &
  - sleep 10

script: npm test
